import Head from "next/head";
import styles from "@/styles/Home.module.css";
import gStyles from "../styles/global.module.css";
import { getData } from "@/firebase/db/getData";
import { useEffect, useState } from "react";
import { addData } from "@/firebase/db/addData";
import { useRouter } from "next/router";

export default function Home({ dataObject }) {
	return (
		<>
			<Head>
				<title>Thai Now</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/images/logo.png" />
			</Head>
			<main className={styles.main}>
				<p>index</p>
			</main>
		</>
	);
}

export async function getServerSideProps(context) {
	const data = await getData();
	const dataObject = JSON.parse(JSON.stringify(data));

	console.log("SSR data:", dataObject);

	return {
		props: { dataObject },
	};
}
