import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { getData } from "@/firebase/db/getData";
import { useEffect, useState } from "react";
import { addData } from "@/firebase/db/addData";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ dataObject }) {
	const [data, setData] = useState([]);

	const router = useRouter();

	useEffect(() => {
		// if (location.pathname === "/") router.push("/home");
		// else router.push(location.pathname);
		fetchData();
	}, []);

	async function fetchData() {
		const data = await getData();
		console.log("fetchData", data);
		setData(data);
	}

	function handleAddUser() {
		addData();
	}

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				{dataObject.map((item, idx) => {
					return <h1 key={idx}>{item.greet}</h1>;
				})}
				<button onClick={handleAddUser}>add new data</button>
			</main>
		</>
	);
}

export async function getServerSideProps(context) {
	const data = await getData();
	const dataObject = JSON.parse(JSON.stringify(data));

	console.log("SSR data:", dataObject);

	return {
		props: { dataObject },
	};
}
